name: Playwright Tests

on:
  push:
    branches:
      - master
      - dev
      - t300-main
      - develop-t300
  pull_request:
    branches:
      - master
      - t300-main
      - develop-t300

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      MANAGER_EMAIL: ${{ secrets.MANAGER_EMAIL }}
      MANAGER_PASSWORD: ${{ secrets.MANAGER_PASSWORD }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: pip install -r t300/requirements.txt

      - name: Install Playwright browsers
        run: playwright install --with-deps

      - name: Run tests
        run: pytest t300
